"""RAPID step 1: our own baselines for "does a large crystal (score 4) form?" on unseen amines.
Data: 0045.perovskitedata.csv (Pendleton et al. 2020, github.com/ipendlet/MLScripts, CC-BY 4.0), score-0 (unrecorded) rows dropped.
Evaluation: leave-one-amine-out (train on 44 amines, predict the held-out one) vs random 5-fold split (same rows).
Usage: python rapid/loo_baseline.py   (-> rapid/results_loo_baseline.md)"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import matthews_corrcoef, roc_auc_score
from sklearn.model_selection import LeaveOneGroupOut, StratifiedKFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from util import md  # noqa: E402

CSV = ROOT / "data" / "MLScripts" / "temp_densityconc" / "0045.perovskitedata.csv"
OUT = ROOT / "results_loo_baseline.md"
AMINE = "_rxn_organic-inchikey"
RXN = ["_rxn_M_acid", "_rxn_M_inorganic", "_rxn_M_organic", "_rxn_temperatureC_actual_bulk", "_rxn_mixingtime1S",
       "_rxn_mixingtime2S", "_rxn_reactiontimeS", "_rxn_stirrateRPM"]
SEED = 0


def load():
    d = pd.read_csv(CSV, comment="#", low_memory=False)
    d = d[d._out_crystalscore > 0].reset_index(drop=True)
    feat = [c for c in d if c.startswith("_feat_")]
    return d, feat, (d._out_crystalscore == 4).astype(int).values


MODELS = {
    "LightGBM": lambda: LGBMClassifier(n_estimators=300, learning_rate=0.05, num_leaves=31, random_state=SEED, verbose=-1),
    "로지스틱 회귀": lambda: make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, C=1.0)),
}


def evaluate(X, y, groups, splitter, make):
    p = np.zeros(len(y))
    for tr, te in splitter.split(X, y, groups):
        p[te] = make().fit(X.iloc[tr], y[tr]).predict_proba(X.iloc[te])[:, 1]
    return p


def per_group(y, p, groups):
    """Mean over held-out amines of MCC (threshold 0.5) and ROC-AUC (amines with both classes only)."""
    mcc, auc = [], []
    for g in np.unique(groups):
        m = groups == g
        mcc.append(matthews_corrcoef(y[m], p[m] >= 0.5))
        if 0 < y[m].mean() < 1:
            auc.append(roc_auc_score(y[m], p[m]))
    return np.mean(mcc), np.mean(auc), len(auc)


def main():
    d, feat, y = load()
    groups = d[AMINE].values
    rows = []
    for fname, cols in (("반응 조건만", RXN), ("반응 조건 + 아민 물성", RXN + feat)):
        X = d[cols]
        for mname, make in MODELS.items():
            for sname, splitter in (("아민 하나 빼기", LeaveOneGroupOut()), ("무작위 5겹", StratifiedKFold(5, shuffle=True, random_state=SEED))):
                p = evaluate(X, y, groups, splitter, make)
                m, a, n_auc = per_group(y, p, groups)
                rows.append({"입력": fname, "모델": mname, "평가": sname, "MCC (전체)": matthews_corrcoef(y, p >= 0.5),
                             "AUC (전체)": roc_auc_score(y, p), "MCC (아민별 평균)": m, f"AUC (아민별 평균)": a})
                print(rows[-1], flush=True)
    R = pd.DataFrame(rows).round(3)
    info = (f"{len(d)} experiments (score-0 dropped), {d[AMINE].nunique()} amines, score-4 share {y.mean():.3f}; "
            f"amines with both outcomes (AUC defined): {n_auc}. Random classifier: MCC 0, AUC 0.5.\n\n")
    OUT.write_text("# RAPID step 1: our baselines (generated by rapid/loo_baseline.py)\n\n" + info + md(R, index=False) + "\n",
                   encoding="utf-8")


if __name__ == "__main__":
    main()
