"""RAPID step 4-1 and 4-2 (plan: rapid/README.md, "4단계 계획"). Same data, splits, tuning and seeds as step 3.
4-1: MCC, BCR, top-20% 4-point share, experiments to the first 4-point result (report only).
4-2: fixed experiment budget k* chosen on validation amines (smallest k with AUC(k) >= AUC(32) - 0.03), checked on test amines.
Usage: python rapid/step4.py   (-> rapid/results_step4.md)"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from joblib import Parallel, delayed
from sklearn.metrics import balanced_accuracy_score, matthews_corrcoef

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from step3 import (AMINE, KS, REPS, SEED, TOP, auc, boot, fmt, gain, lgbm, part_a, prepare, shots_runs,  # noqa: E402
                   tune_b)
from step1 import md  # noqa: E402

OUT = ROOT / "results_step4.md"
VAL_REPS, TOL, N_BOOT = 3, 0.03, 1000


def metrics(y, p):
    """All step-4 metrics on one amine's scored rows (y: 0/1 actual, p: predicted probability of a 4-point result)."""
    k = max(1, int(round(TOP * len(y))))
    order = np.argsort(-p, kind="stable")
    hits = np.flatnonzero(y[order] == 1)
    m = y.sum()
    return {"auc": auc(y, p), "gain": gain(y, p), "top20": y[order[:k]].mean(), "base": y.mean(),
            "mcc": matthews_corrcoef(y, p >= 0.5), "bcr": balanced_accuracy_score(y, p >= 0.5) if 0 < m < len(y) else np.nan,
            "first": hits[0] + 1 if m else np.nan, "first_random": (len(y) + 1) / (m + 1) if m else np.nan}


def val_curve(train, d, val_amines, cfg, w, fold, X):
    """Mean AUC over validation amines at every k, scored on the rows left after 32 shots (same rows for every k)."""
    rows = []
    for g in val_amines:
        s = d[d[AMINE] == g].reset_index(drop=True)
        if s.y.sum() == 0 or len(s) - KS[-1] < 10:
            continue
        for r in range(VAL_REPS):
            perm = np.random.default_rng([SEED, 55, fold, r]).permutation(len(s))
            P = shots_runs(train, s, cfg, w, perm, KS, X)
            common = perm[KS[-1]:]
            rows += [{"k": k, "auc": auc(s.y.to_numpy()[common], P[k][common])} for k in KS]
    return pd.DataFrame(rows).groupby("k").auc.mean()


def test_amine(train, s, g, cfg, w, fold, kstar, X):
    y = s.y.to_numpy()
    p0 = lgbm(cfg).fit(train[X], train.y).predict_proba(s[X])[:, 1]
    ks = sorted({k for k in (8, 10, kstar, KS[-1]) if len(s) - k >= 10})
    rows = []
    for r in range(REPS):
        perm = np.random.default_rng([SEED, 7, fold, r, len(s)]).permutation(len(s))  # same shot orders as step 3
        P = {0: p0, **shots_runs(train, s, cfg, w, perm, ks, X)}
        for k in [0] + ks:
            rows.append({"amine": g, "rep": r, "k": k, **metrics(y[perm[k:]], P[k][perm[k:]])})
        if kstar in P and KS[-1] in P:
            common = perm[KS[-1]:]
            rows.append({"amine": g, "rep": r, "k": -1, "kstar": kstar,
                         "auc_kstar": auc(y[common], P[kstar][common]), "auc_32": auc(y[common], P[KS[-1]][common])})
    return rows


def main():
    d, feat, XG = prepare()
    rng = np.random.default_rng(SEED)
    s = [f"# RAPID step 4-1, 4-2 results (generated by rapid/step4.py)\n\nSame data, splits, tuning and shot orders as step 3. "
         f"Cells: mean over amines [95% amine bootstrap, {N_BOOT} resamples]. MCC and BCR use the 0.5 threshold "
         "(random: MCC 0, BCR 0.5). 'first' = position of the first 4-point result when following the ranking; "
         "'first_random' = its expected value under a random order.\n"]

    # A (known amine), same split and model as step 3
    _, _, best, sizes, T = part_a(d, XG)
    A = pd.DataFrame({g: metrics(t.y.to_numpy(), t.p.to_numpy()) for g, t in T.groupby(AMINE) if t.y.sum() > 0}).T
    ia = [rng.integers(0, len(A), len(A)) for _ in range(N_BOOT)]
    cols = ["auc", "gain", "top20", "base", "mcc", "bcr", "first", "first_random"]
    s.append(f"## A. 이미 실험한 아민 (아민 {len(A)}종, test rows {sizes['test']})\n"
             + md(pd.DataFrame([{c: fmt(boot(A[c], ia)) for c in cols}]), index=False) + "\n")

    # B (new amine): replay step 3's outer folds and tuning, then the validation curve for k*
    amines = np.array(sorted(d[AMINE].unique()))
    rng_b = np.random.default_rng(SEED)
    outer = {g: i % 5 for i, g in enumerate(rng_b.permutation(amines))}
    rows, folds = [], []
    for f in range(5):
        test_a = [g for g in amines if outer[g] == f]
        rest_a = rng_b.permutation([g for g in amines if outer[g] != f])
        n_val = int(round(len(rest_a) * 0.25))
        val_a, tr_a = rest_a[:n_val], rest_a[n_val:]
        train_only = d[d[AMINE].isin(tr_a)]
        cfg, w = tune_b(train_only, val_a, d, f, XG)
        curve = val_curve(train_only, d, val_a, cfg, w, f, XG)
        kstar = int(min(k for k in KS if curve[k] >= curve[KS[-1]] - TOL))
        folds.append({"fold": f, **cfg, "weight": w, "k*": kstar, **{f"val AUC k={k}": round(curve[k], 3) for k in (4, 8, 16, 32)}})
        train = d[d[AMINE].isin(np.concatenate([tr_a, val_a]))]
        res = Parallel(n_jobs=-1)(delayed(test_amine)(train, d[d[AMINE] == g].reset_index(drop=True), g, cfg, w, f, kstar, XG)
                                  for g in test_a if d.loc[d[AMINE] == g, "y"].sum() > 0)
        rows += [x for r in res for x in r]
    R = pd.DataFrame(rows)
    amines_b = sorted(R.amine.unique())
    ib = [rng.integers(0, len(amines_b), len(amines_b)) for _ in range(N_BOOT)]
    per = R[R.k >= 0].groupby(["amine", "k"])[cols].mean()
    table = []
    for k in sorted(R[R.k >= 0].k.unique()):
        v = per.xs(k, level="k").reindex(amines_b)
        table.append({"k": int(k), "아민 수": int(v.auc.notna().sum()), **{c: fmt(boot(v[c], ib)) for c in cols}})
    st = R[R.k == -1].groupby("amine")[["kstar", "auc_kstar", "auc_32"]].mean().reindex(amines_b)
    diff = boot(st.auc_kstar - st.auc_32, ib)
    kmean = st.kstar.mean()
    verdict = "충족" if diff[0] >= -TOL and kmean < KS[-1] else "미달"
    s.append(f"## B. 처음 보는 아민 (아민 {len(amines_b)}종, 아민마다 무작위 실험 순서 {REPS}가지)\n"
             "k = 새 아민으로 먼저 해 본 실험 수 (k = 10은 PLATIPUS 비교용)\n\n"
             + md(pd.DataFrame(table), index=False) + "\n\n"
             f"## 4-2. 멈출 시점 ① 고정 횟수 (판정: **{verdict}**)\n"
             f"검증 아민에서 AUC(k) ≥ AUC(32) − {TOL}인 가장 작은 k를 k*로 정함. 시험 아민 평균 k* = {kmean:.1f}, "
             f"AUC(k*) − AUC(32) = {fmt(diff)} (32번 이후 남은 같은 조건에서 비교; 기준: 평균 ≥ −{TOL}, 평균 k* < 32)\n\n"
             + md(pd.DataFrame(folds), index=False) + "\n")
    OUT.write_text("\n".join(s), encoding="utf-8")
    print(f"4-2 {verdict}")
    print("\n".join(s[1:]))


if __name__ == "__main__":
    main()
