"""RAPID step 1: baselines for "does a large crystal (score 4) form?" on unseen amines.
(a) summary of the original paper's model logs (Pendleton et al. 2020, ML_Logs.zip), (b) our own baselines:
leave-one-amine-out vs random 5-fold split on the same rows.
Data: github.com/ipendlet/MLScripts (CC-BY 4.0), cloned into rapid/data/MLScripts. Score-0 (unrecorded) rows dropped.
Usage: python rapid/step1.py   (about 3 min -> rapid/results_step1.md)"""
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import matthews_corrcoef, roc_auc_score
from sklearn.model_selection import LeaveOneGroupOut, StratifiedKFold
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "data" / "MLScripts" / "temp_densityconc"
OUT = ROOT / "results_step1.md"
AMINE = "_rxn_organic-inchikey"
RXN = ["_rxn_M_acid", "_rxn_M_inorganic", "_rxn_M_organic", "_rxn_temperatureC_actual_bulk", "_rxn_mixingtime1S",
       "_rxn_mixingtime2S", "_rxn_reactiontimeS", "_rxn_stirrateRPM"]
SEED = 0
ORIG_COLS = {"matthewCoef_success mean": "MCC", "f1_success mean": "F1", "precision_success mean": "precision",
             "recall_success mean": "recall"}
MODELS = {
    "LightGBM": lambda: LGBMClassifier(n_estimators=300, learning_rate=0.05, num_leaves=31, random_state=SEED, verbose=-1),
    "로지스틱 회귀": lambda: make_pipeline(StandardScaler(), LogisticRegression(max_iter=2000, C=1.0)),
}


def md(t, index=True):  # markdown table without the tabulate dependency
    t = t.reset_index() if index else t
    rows = [list(map(str, t.columns))] + [list(map(str, r)) for r in t.values.tolist()]
    return "\n".join(["| " + " | ".join(rows[0]) + " |", "|" + "---|" * len(rows[0])]
                     + ["| " + " | ".join(r) + " |" for r in rows[1:]])


def load():
    d = pd.read_csv(SRC / "0045.perovskitedata.csv", comment="#", low_memory=False)
    d = d[d._out_crystalscore > 0].reset_index(drop=True)
    feat = [c for c in d if c.startswith("_feat_")]
    return d, feat, (d._out_crystalscore == 4).astype(int).values


def original():
    """Original paper: best leave-one-amine-out result per model, next to its standard-split result."""
    def read(z, name):
        rows = [pd.read_csv(z.open(f)).rename(columns={"Unnamed: 0": "data", "Unnamed: 1": "features"}).assign(model=f.split("/")[-2])
                for f in z.namelist() if f.endswith("/" + name) and "__MACOSX" not in f]
        return pd.concat(rows)[["model", "data", "features", *ORIG_COLS]].rename(columns=ORIG_COLS)
    with zipfile.ZipFile(SRC / "ML_Logs.zip") as z:
        T = read(z, "LeaveOneOut_Summary.csv").merge(read(z, "StandardTestTrain_Summary.csv"),
                                                     on=["model", "data", "features"], suffixes=(" LOO", " split"))
    return T.sort_values("MCC LOO", ascending=False).groupby("model").head(1).round(3)


def predict(X, y, groups, splitter, make):
    p = np.zeros(len(y))
    for tr, te in splitter.split(X, y, groups):
        p[te] = make().fit(X.iloc[tr], y[tr]).predict_proba(X.iloc[te])[:, 1]
    return p


def per_amine(y, p, groups):
    """Mean over amines of MCC (threshold 0.5) and ROC-AUC (amines with both outcomes only)."""
    mcc, auc = [], []
    for g in np.unique(groups):
        m = groups == g
        mcc.append(matthews_corrcoef(y[m], p[m] >= 0.5))
        if 0 < y[m].mean() < 1:
            auc.append(roc_auc_score(y[m], p[m]))
    return np.mean(mcc), np.mean(auc), len(auc)


def main():
    best = original()
    d, feat, y = load()
    groups = d[AMINE].values
    rows = []
    for fname, cols in (("반응 조건만", RXN), ("반응 조건 + 아민 물성", RXN + feat)):
        for mname, make in MODELS.items():
            for sname, splitter in (("아민 하나 빼기", LeaveOneGroupOut()), ("무작위 5겹", StratifiedKFold(5, shuffle=True, random_state=SEED))):
                p = predict(d[cols], y, groups, splitter, make)
                m, a, n_auc = per_amine(y, p, groups)
                rows.append({"입력": fname, "모델": mname, "평가": sname, "MCC (전체)": matthews_corrcoef(y, p >= 0.5),
                             "AUC (전체)": roc_auc_score(y, p), "MCC (아민별 평균)": m, "AUC (아민별 평균)": a})
    R = pd.DataFrame(rows).round(3)
    OUT.write_text(
        "# RAPID step 1 results (generated by rapid/step1.py)\n\n"
        f"{len(d)} experiments (score-0 dropped), {d[AMINE].nunique()} amines, score-4 share {y.mean():.3f}; "
        f"amines with both outcomes (AUC defined): {n_auc}. Random classifier: MCC 0, AUC 0.5.\n\n"
        f"## our baselines\n{md(R, index=False)}\n\n"
        "## original paper (best leave-one-amine-out per model)\n"
        "LOO = leave-one-amine-out (mean over held-out amines), split = standard train/test; "
        "data: sampled = stratified sample, all = full data.\n\n"
        f"{md(best, index=False)}\n", encoding="utf-8")
    print(md(R, index=False))


if __name__ == "__main__":
    main()
