"""RAPID variable importance (SHAP, LightGBM's built-in pred_contrib) for the step-3 models.
Model 1 "known amines": trained on all amines (what drives predictions when the amine has been seen).
Model 2 "new amine": for each of step 3's outer folds, trained without the test amines; SHAP on the test amines' rows.
SHAP values are in log-odds of a 4-point result. Descriptive only (no verdict).
Usage: python rapid/xai.py   (-> rapid/results_xai.md, rapid/figures/xai_*.png)"""
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
from step3 import AMINE, SEED, lgbm, prepare  # noqa: E402
from step1 import md  # noqa: E402

OUT, FIG = ROOT / "results_xai.md", ROOT / "figures"
NAMES = {"_rxn_M_inorganic": "PbI₂ 농도", "_rxn_M_organic": "아민 농도", "_rxn_M_acid": "포름산 농도", "amine_pb": "아민/PbI₂ 몰비",
         "acid_pb": "포름산/PbI₂ 몰비", "_rxn_temperatureC_actual_bulk": "온도", "_rxn_reactiontimeS": "반응 시간",
         "_rxn_stirrateRPM": "교반 속도"}
BLUE, ORANGE, GRAY, INK = "#2a78d6", "#eb6834", "#9a9893", "#52514e"


def name(c):
    return NAMES.get(c, "아민: " + c.replace("_feat_", ""))


def shap(model, X):
    return pd.DataFrame(model.booster_.predict(X, pred_contrib=True)[:, :-1], columns=X.columns, index=X.index)


def summary(S, X):
    imp = S.abs().mean().sort_values(ascending=False)
    cond = [c for c in X if c in NAMES]
    share = imp[cond].sum() / imp.sum()
    return imp, share


def main():
    FIG.mkdir(exist_ok=True)
    d, feat, X = prepare()
    cfg = {"num_leaves": 31, "n_estimators": 400}  # step 3 A's choice

    # model 1: all amines
    m1 = lgbm(cfg).fit(d[X], d.y)
    S1 = shap(m1, d[X])
    imp1, share1 = summary(S1, d[X])

    # model 2: step 3's outer folds (test amines unseen)
    amines = np.array(sorted(d[AMINE].unique()))
    outer = {g: i % 5 for i, g in enumerate(np.random.default_rng(SEED).permutation(amines))}
    parts = []
    for f in range(5):
        te = d[AMINE].map(outer) == f
        m = lgbm({"num_leaves": 15, "n_estimators": 400}).fit(d.loc[~te, X], d.y[~te])
        parts.append(shap(m, d.loc[te, X]))
    S2 = pd.concat(parts).loc[d.index]
    imp2, share2 = summary(S2, d[X])

    top = pd.DataFrame({"이미 본 아민 (모델 1)": imp1.round(3), "처음 보는 아민 (모델 2)": imp2.round(3)})
    top.index = [name(c) for c in top.index]
    top = top.sort_values("이미 본 아민 (모델 1)", ascending=False).head(15)

    # direction for condition variables: mean SHAP by quintile of the variable (model 1)
    rows = []
    for c in ["acid_pb", "amine_pb", "_rxn_M_inorganic", "_rxn_M_acid", "_rxn_M_organic"]:
        q = pd.qcut(d[c], 5, duplicates="drop")
        v = S1[c].groupby(q, observed=True).mean()
        rows.append({"변수": name(c), "구간 (5분위)": " | ".join(str(i) for i in v.index.astype(str)),
                     "평균 SHAP (구간별)": " | ".join(f"{x:+.2f}" for x in v.values)})

    fig, ax = plt.subplots(1, 2, figsize=(15, 6))
    for a, imp, title in ((ax[0], imp1, "(a) 이미 본 아민 모델 (전체 아민으로 학습)"), (ax[1], imp2, "(b) 처음 보는 아민 모델 (시험 아민 제외 학습)")):
        t = imp.head(12)[::-1]
        a.barh([name(c) for c in t.index], t.values, color=[BLUE if c in NAMES else ORANGE for c in t.index], height=0.6)
        a.set(title=title, xlabel="평균 |SHAP| (4점 log-odds)")
        a.spines[["top", "right"]].set_visible(False)
    ax[1].legend(handles=[plt.Rectangle((0, 0), 1, 1, color=BLUE), plt.Rectangle((0, 0), 1, 1, color=ORANGE)],
                 labels=["실험 조건", "아민 분자 특성"], frameon=False, loc="lower right")
    fig.suptitle("변수 중요도 (SHAP): 4점 확률 예측에 각 변수가 얼마나 영향을 주나")
    fig.tight_layout()
    fig.savefig(FIG / "xai_importance.png", dpi=110)
    plt.close(fig)

    fig, ax = plt.subplots(1, 3, figsize=(16, 4.5))
    for a, c in zip(ax, ["acid_pb", "amine_pb", "_rxn_M_inorganic"]):
        a.scatter(d[c], S1[c], s=4, alpha=0.3, c=np.where(d.y == 1, BLUE, GRAY))
        if c.endswith("_pb"):
            a.set_xscale("log")  # ratios explode when PbI2 is tiny
            a.xaxis.set_major_formatter(matplotlib.ticker.FuncFormatter(lambda v, _: f"{v:g}"))  # font lacks the math minus
        a.axhline(0, color=INK, lw=0.8)
        a.set(xlabel=name(c), ylabel="SHAP (+ = 4점 쪽으로)", title=name(c))
        a.spines[["top", "right"]].set_visible(False)
    fig.suptitle("실험 조건이 예측을 어느 방향으로 움직이나 (이미 본 아민 모델; 파랑 = 실제 4점, 회색 = 1~3점; 몰비는 로그 눈금)")
    fig.tight_layout()
    fig.savefig(FIG / "xai_dependence.png", dpi=110)
    plt.close(fig)

    OUT.write_text(
        "# RAPID variable importance (generated by rapid/xai.py)\n\n"
        "SHAP: 각 실험의 예측(4점일 log-odds)을 변수별 기여로 나눈 값. 평균 |SHAP|이 클수록 예측에 많이 쓰인 변수. "
        "인과 관계가 아니라 모델이 무엇을 보고 예측하는지에 대한 설명입니다.\n\n"
        f"그림: [중요도](figures/xai_importance.png), [방향](figures/xai_dependence.png)\n\n"
        f"## 실험 조건 vs 아민 특성의 비중\n- 이미 본 아민 모델: 실험 조건 {share1:.0%}, 아민 특성 {1 - share1:.0%}\n"
        f"- 처음 보는 아민 모델: 실험 조건 {share2:.0%}, 아민 특성 {1 - share2:.0%}\n\n"
        f"## 상위 15개\n{md(top)}\n\n## 실험 조건의 방향 (이미 본 아민 모델, 변수 5분위별 평균 SHAP)\n{md(pd.DataFrame(rows), index=False)}\n",
        encoding="utf-8")
    print(OUT.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
