"""v2 diagnostics on the test split: predicted vs actual, error by PCE band, what the top-predicted devices
really achieve, and error by year / architecture / HTL.
Usage: python models/v2/diagnose.py   (tables -> models/v2/diagnostics.md, plot -> models/v2/figures/)"""
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_absolute_error, r2_score

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from config import v2 as C
from models.v2.model_v2 import ALL, Model, clean, make_features
from src.data import split_from_file
from src.features import md

OUT = Path(__file__).resolve().parent
RESULTS = OUT / "diagnostics.md"
BEST = json.loads((OUT / "best_params.json").read_text(encoding="utf-8"))
BANDS = [-np.inf, 5, 10, 15, 18, np.inf]
BAND_LABELS = ["≤5", "5-10", "10-15", "15-18", ">18"]  # pd.cut is right-inclusive: (5, 10] etc.


def out(text="", console=False):
    with RESULTS.open("a", encoding="utf-8") as f:
        f.write(str(text) + "\n")
    if console:
        print(text, flush=True)


def by_group(te, col):
    g = te.groupby(col, dropna=False)
    return pd.DataFrame({"n": g.size(), "MAE": g.err.apply(lambda e: e.abs().mean()),
                         "mean error (pred-actual)": g.err.mean(), "actual mean": g.pce.mean()}).round(2)


def main():
    RESULTS.write_text("# v2 diagnostics (generated by models/v2/diagnose.py)\n\n", encoding="utf-8")
    df, _ = clean()
    F = make_features(df)
    tr_i, te_i = split_from_file(F["doi"])  # splits/doi_split.csv, same roles as model_v2.py
    tr, te = F.iloc[tr_i], F.iloc[te_i].copy()
    m = Model(BEST["model"], BEST["params"], BEST["missing"] == "median+flag", ALL).fit(tr, tr.pce)
    te["pred"] = m.predict(te)
    te["err"] = te.pred - te.pce
    mae, r2 = mean_absolute_error(te.pce, te.pred), r2_score(te.pce, te.pred)
    out(f"test {len(te)} rows / {te.doi.nunique()} papers: MAE {mae:.3f}, R2 {r2:.3f}", console=True)

    fig, ax = plt.subplots(figsize=(5.2, 5))
    ax.scatter(te.pce, te.pred, s=5, alpha=0.25)
    ax.plot([0, 25], [0, 25], "k--", lw=1)
    ax.set_xlim(0, 25)
    ax.set_ylim(0, 25)
    ax.set_xlabel("actual PCE (%)")
    ax.set_ylabel("predicted PCE (%)")
    ax.set_title(f"v2 test: MAE {mae:.2f}, R² {r2:.2f}")
    fig.tight_layout()
    fig.savefig(OUT / "figures" / "pred_vs_actual.png", dpi=110)
    plt.close(fig)
    out(f"predicted range: p1 {te.pred.quantile(0.01):.1f}, p99 {te.pred.quantile(0.99):.1f};"
        f" actual range: p1 {te.pce.quantile(0.01):.1f}, p99 {te.pce.quantile(0.99):.1f}")

    te["band"] = pd.cut(te.pce, BANDS, labels=BAND_LABELS)
    b = by_group(te, "band").assign(share=lambda t: (t.n / len(te)).round(3))
    out("\n## error by actual PCE band\n" + md(b))

    rows = []
    for name, s in [("all test", te)] + [(f"top {q:.0%} predicted", te[te.pred >= te.pred.quantile(1 - q)])
                                          for q in (0.1, 0.2)]:
        p = s.pce
        rows.append((name, len(s), p.mean(), p.quantile(0.1), p.median(), p.quantile(0.9),
                     (p >= 15).mean(), (p >= 18).mean(), (p < 5).mean()))
    t = pd.DataFrame(rows, columns=["group", "n", "actual mean", "p10", "median", "p90", ">=15%", ">=18%", "<5%"])
    out("\n## actual PCE of devices the model ranks highest\n" + md(t.round(3), index=False))

    for col in ["year", "arch"]:
        out(f"\n## error by {col}\n" + md(by_group(te, col)))
    keep = tr.htl.value_counts().index[:C.TOP_N["htl"]]
    te["htl_top"] = te.htl.where(te.htl.isin(keep), "other")
    out("\n## error by HTL (top 6 in train + other)\n" + md(by_group(te, "htl_top")))

    out(f"\nunder-predicted (> 18% actual): mean error {b.loc['>18', 'mean error (pred-actual)']:+.2f};"
        f" over-predicted (<= 5% actual): {b.loc["≤5", "mean error (pred-actual)"]:+.2f}", console=True)
    out(f"top 10% predicted: actual mean {t['actual mean'][1]:.1f} vs all {t['actual mean'][0]:.1f};"
        f" share >= 15%: {t['>=15%'][1]:.0%} vs {t['>=15%'][0]:.0%}", console=True)
    out(f"details: {RESULTS.relative_to(ROOT)}", console=True)


if __name__ == "__main__":
    main()
