"""Past-only v2 tuning: pick hyperparameters using papers up to 2017 only (train-role papers in splits/doi_split.csv),
so experiments 1 and 2 never depend on settings chosen with 2018+ data.
Usage: python models/v2/tune_past.py   (-> models/v2/best_params_past.json, table -> models/v2/tuning_past.md)
best_params.json (chosen with all years) is left as is and is not used by the experiments."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from config import exp1 as E
from config import v2 as C
from models.v2.model_v2 import ALL, clean, make_features, tune
from src.data import split_from_file
from src.features import md

OUT = Path(__file__).resolve().parent
PAST = OUT / "best_params_past.json"


def past_train():
    F = make_features(clean()[0])
    F = F[F.year <= E.CUTOFF_YEAR].reset_index(drop=True)
    assert F.year.max() <= E.CUTOFF_YEAR
    tr_i, _ = split_from_file(F["doi"])
    return F.iloc[tr_i].reset_index(drop=True)


def main():
    tr = past_train()
    print(f"past tuning data: {len(tr)} rows / {tr.doi.nunique()} papers, years {tr.year.min():.0f}-{tr.year.max():.0f}")
    t = tune(tr, ALL)
    (OUT / "tuning_past.md").write_text(
        f"# v2 tuning on <= {E.CUTOFF_YEAR} train-role papers (generated by models/v2/tune_past.py)\n\n"
        + md(t.assign(cv_MAE=t.cv_MAE.round(3), cv_R2=t.cv_R2.round(3)), index=False) + "\n", encoding="utf-8")
    best = t.loc[t["cv_MAE"].idxmin()]
    PAST.write_text(json.dumps({
        "model": best["model"], "missing": best["missing"], "params": best["params"], "features": C.GROUPS,
        "cv_MAE": round(best["cv_MAE"], 4), "cv_R2": round(best["cv_R2"], 4),
        "data": {"years": f"<= {E.CUTOFF_YEAR}", "role": "train (splits/doi_split.csv)",
                 "rows": len(tr), "papers": int(tr.doi.nunique())},
        "cv": {"folds": C.CV_FOLDS, "seed": C.SEED}}, indent=2), encoding="utf-8")
    print(f"best: {best['model']} ({best['missing']}) {best['params']}  CV MAE {best['cv_MAE']:.3f} R2 {best['cv_R2']:.3f}")
    print(f"saved {PAST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
