"""D: 'score -> probability of reaching a target PCE' tables, built from out-of-fold (OOF) predictions on the v2 train
split and checked on the v2 test split. Compares v2 with method B (train without PCE < 5% rows).
Usage: python pce/models/v2/calibration.py   (tables -> models/v2/calibration.md, plot -> models/v2/figures/calibration.png,
lookup table for the recommender -> models/v2/calibration_table.csv)"""
import json
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.isotonic import IsotonicRegression
from sklearn.model_selection import GroupKFold

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from config import v2 as C
from models.v2.model_v2 import ALL, Model, clean, make_features
from src.data import split_from_file
from src.features import md

OUT = Path(__file__).resolve().parent
RESULTS = OUT / "calibration.md"
BEST = json.loads((OUT / "best_params.json").read_text(encoding="utf-8"))
TARGETS = [15, 18, 20]
# score-rank bins, as top-share ranges of the OOF score distribution
BINS = [(0, 0.01), (0.01, 0.05), (0.05, 0.10), (0.10, 0.20), (0.20, 0.30), (0.30, 0.50), (0.50, 1.0)]
LOW_PCE = 5.0


def out(text="", console=False):
    with RESULTS.open("a", encoding="utf-8") as f:
        f.write(str(text) + "\n")
    if console:
        print(text, flush=True)


def fit(train, drop_low):
    t = train[train.pce >= LOW_PCE] if drop_low else train
    return Model(BEST["model"], BEST["params"], BEST["missing"] == "median+flag", ALL).fit(t, t.pce)


def oof(tr, drop_low):
    p = np.empty(len(tr))
    for a, b in GroupKFold(C.CV_FOLDS).split(tr, groups=tr["doi"]):
        p[b] = fit(tr.iloc[a], drop_low).predict(tr.iloc[b])
    return p


def table(score, pce, cuts):
    """Observed share reaching each target, per score bin (bins defined by fixed score cut-offs)."""
    rows = []
    for (lo, hi), (c_hi, c_lo) in zip(BINS, cuts):
        m = (score <= c_hi) & (score > c_lo)
        rows.append({"score rank": f"top {lo:.0%}-{hi:.0%}", "n": int(m.sum()),
                     **{f">={t}%": pce[m].ge(t).mean() if m.any() else np.nan for t in TARGETS}})
    return pd.DataFrame(rows)


def main():
    RESULTS.write_text("# target-PCE probability calibration (generated by models/v2/calibration.py)\n\n", encoding="utf-8")
    df, _ = clean()
    F = make_features(df)
    tr_i, te_i = split_from_file(F["doi"])  # splits/doi_split.csv, same roles as model_v2.py
    tr, te = F.iloc[tr_i].reset_index(drop=True), F.iloc[te_i].reset_index(drop=True)
    out(f"train {len(tr)} rows (OOF via GroupKFold {C.CV_FOLDS}); test {len(te)} rows", console=True)
    base = {t: f"{tr.pce.ge(t).mean():.1%} / {te.pce.ge(t).mean():.1%}" for t in TARGETS}
    out("base rate (train / test): " + ", ".join(f">={t}%: {v}" for t, v in base.items()))

    lookup, curves, summary = [], {}, []
    for name, drop_low in [("v2", False), (f"B (train without PCE < {LOW_PCE:g}%)", True)]:
        s_oof = pd.Series(oof(tr, drop_low))
        s_te = pd.Series(fit(tr, drop_low).predict(te))
        q = s_oof.quantile
        cuts = [(q(1 - lo) if lo > 0 else np.inf, q(1 - hi) if hi < 1 else -np.inf) for lo, hi in BINS]
        t_oof, t_te = table(s_oof, tr.pce, cuts), table(s_te, te.pce, cuts)
        both = t_oof.merge(t_te, on="score rank", suffixes=(" OOF", " test"))
        cols = ["score rank", "n OOF"] + [f">={t}% OOF" for t in TARGETS] + ["n test"] + [f">={t}% test" for t in TARGETS]
        out(f"\n## {name}: share reaching target by score rank (OOF table, checked on test)\n"
            + md(both[cols].round(3), index=False))

        iso_rows = []
        for t in TARGETS:
            iso = IsotonicRegression(out_of_bounds="clip").fit(s_oof, tr.pce.ge(t))
            p_te = iso.predict(s_te)
            brier = np.mean((p_te - te.pce.ge(t)) ** 2)
            base_brier = np.mean((tr.pce.ge(t).mean() - te.pce.ge(t)) ** 2)
            grid = np.linspace(s_oof.min(), s_oof.max(), 200)
            curves[(name, t)] = (grid, iso.predict(grid))
            # reliability on test: group by predicted probability
            g = pd.DataFrame({"p": p_te, "y": te.pce.ge(t)}).groupby(pd.qcut(p_te, 5, duplicates="drop"), observed=True)
            rel = "; ".join(f"pred {r.p:.2f} -> obs {r.y:.2f}" for _, r in g.mean().iterrows())
            iso_rows.append((t, brier, base_brier, rel))
            for lo, hi in BINS:
                c_hi, c_lo = (q(1 - lo) if lo > 0 else s_oof.max()), q(1 - hi) if hi < 1 else s_oof.min()
                lookup.append({"method": name, "target": t, "score rank": f"top {lo:.0%}-{hi:.0%}",
                               "score from": round(c_lo, 3), "score to": round(c_hi, 3),
                               "probability (OOF)": round(tr.pce[(s_oof > c_lo) & (s_oof <= c_hi)].ge(t).mean(), 3)})
        out(f"\nisotonic (score -> P) fitted on OOF, evaluated on test:\n" + md(pd.DataFrame(
            iso_rows, columns=["target %", "Brier", "Brier (base rate)", "test reliability (5 bins)"]).round(4), index=False))
        summary.append((name, *[f"{both[f'>={t}% test'].iloc[:3].mul(both['n test'].iloc[:3]).sum() / both['n test'].iloc[:3].sum():.0%}"
                                for t in TARGETS]))

    pd.DataFrame(lookup).to_csv(OUT / "calibration_table.csv", index=False)
    fig, axes = plt.subplots(1, len(TARGETS), figsize=(13, 3.8))
    for ax, t in zip(axes, TARGETS):
        for (name, tt), (x, y) in curves.items():
            if tt == t:
                ax.plot(x, y, label=name)
        ax.set_title(f"P(PCE >= {t}%) vs model score (isotonic, OOF)", fontsize=9)
        ax.set_xlabel("model score")
        ax.set_ylim(0, 1)
    axes[0].legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(OUT / "figures" / "calibration.png", dpi=110)
    plt.close(fig)

    out("\n=== calibration summary: observed share in the top 10% scores on test ===", console=True)
    out(f"{'base rate (test)':34s} " + "  ".join(f">={t}%: {te.pce.ge(t).mean():.0%}" for t in TARGETS), console=True)
    for name, *v in summary:
        out(f"{name:34s} " + "  ".join(f">={t}%: {x}" for t, x in zip(TARGETS, v)), console=True)
    out(f"details: {RESULTS.relative_to(ROOT)}  lookup: models/v2/calibration_table.csv", console=True)


if __name__ == "__main__":
    main()
